# Generated by Django 4.0.2 on 2022-02-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=40)),
                ('disease', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
            ],
        ),
    ]
